---

- name: Copy haproxy configuration
  template:
    dest: /etc/apiserver-haproxy.cfg
    src: haproxy.cfg.j2
    owner: root
    group: root
    mode: 0644
  register: haproxy_config

- name: apiserver container
  docker_container:
    name: apiserver-haproxy
    image: haproxy:3.2.4
    volumes:
      - "/etc/apiserver-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    state: "started"
    restart_policy: "always"
    network_mode: "host"
    recreate: "{{ true if haproxy_config.changed else false }}"
    restart: "{{ true if haproxy_config.changed else false }}"
  retries: 3
  delay: 10

- name: Add hosts files entries
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1 {{ kubernetes_control_plane_host }}$"
    line: "127.0.0.1 {{ kubernetes_control_plane_host }}"
    state: present
  when: kubernetes_add_hosts_entries
