---

- name: Firewall Configuration for Kubernetes
  ufw:
    direction: in
    rule: allow
    proto: any
    from_ip: "{{ item }}"
  loop: "{{ kubernetes_mgmt_nets|default([]) }}"

- name: Allow all forwarding
  ufw:
    route: true
    rule: allow

- name: Allow all outbound
  ufw:
    direction: out
    rule: allow
