---

- name: Package install
  include_tasks: packages.yml

- name: Firewall configuration
  include_tasks: firewall.yml

- name: apiserver configuration
  include_tasks: apiserver.yml

- name: System Configuration
  include_tasks: system.yml

- name: Manager setup
  include_tasks: manager_setup.yml
  when: "kubernetes_manager | default(false)"

- name: Worker setup
  include_tasks: worker_setup.yml

- name: Post install tasks
  include_tasks: post_install.yml
