---

- name: Primary node configuration
  include_tasks: manager_primary.yml
  when: inventory_hostname == kubernetes_primary_node

- name: Distribute manager join command
  when:
    - kubernetes_manager_join_run is defined and kubernetes_manager_join_run.stdout|default('') != ''
  set_fact:
    kubernetes_manager_join_command: "{{ kubernetes_manager_join_run.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ play_hosts }}"

- name: Other manager joining
  include_tasks: manager_join.yml
  when: inventory_hostname != kubernetes_primary_node

# Remove master taints
- name: Remove master taints
  command: "kubectl taint nodes --all=true node-role.kubernetes.io/master-"
  when:
    - "inventory_hostname == kubernetes_primary_node"
    - "kubernetes_remove_master_taint|default(false)"
  failed_when: false
  environment:
    http_proxy: ""
    https_proxy: ""

...