---

- name: Primary node configuration
  include_tasks: manager_primary.yml
  when: inventory_hostname == kubernetes_primary_node

- name: Distribute manager join command
  when:
    - kubernetes_manager_join_run is defined and kubernetes_manager_join_run.stdout|default('') != ''
  set_fact:
    kubernetes_manager_join_command: "{{ kubernetes_manager_join_run.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ play_hosts }}"

- name: Other manager joining
  include_tasks: manager_join.yml
  when: inventory_hostname != kubernetes_primary_node

- name: Copy Calico manifest
  copy:
    src: "calico.yml"
    dest: "/etc/kubernetes/calico.yaml"
  when: inventory_hostname == kubernetes_primary_node

- name: Apply Calico manifest
  command: "kubectl apply -f /etc/kubernetes/calico.yaml"
  when: inventory_hostname == kubernetes_primary_node
  environment:
    http_proxy: ""
    https_proxy: ""

- name: Copy dashboard manifest
  copy:
    src: "dashboard.yaml"
    dest: "/etc/kubernetes/dashboard.yaml"
  when: inventory_hostname == kubernetes_primary_node

- name: Apply dashboard manifest
  command: "kubectl apply -f /etc/kubernetes/dashboard.yaml"
  when: inventory_hostname == kubernetes_primary_node
  environment:
    http_proxy: ""
    https_proxy: ""

- name: Copy nginx ingress manifest
  copy:
    src: "ingress-nginx.yaml"
    dest: "/etc/kubernetes/ingress-nginx.yaml"
  when: inventory_hostname == kubernetes_primary_node

- name: Apply ingress-nginx manifest
  command: "kubectl apply -f /etc/kubernetes/ingress-nginx.yaml"
  when: inventory_hostname == kubernetes_primary_node
  environment:
    http_proxy: ""
    https_proxy: ""

...